https://github.com/rreganjr/Requel/issues/32
app compiles and runs.

I updated the ManyToAny mappings across the app, in hibernate 6 you don't add the discriminator column to the inverseJoinColumns in the JoinTable definition, just the id column.

I'm getting some errors, first when adding a new goal I got:

org.springframework.dao.DuplicateKeyException: A different object with the same identifier value was already associated with the session, but after clicking save a few times it worked and I haven't see the same error again.

I'm also seeing this, but maybe it isn't related to the update:

Exception in thread "taskExecutor-6" java.lang.RuntimeException: failed to find colocation in synset defintions with update#n#1 and test
	at com.rreganjr.nlp.dictionary.impl.repository.jpa.JpaDictionaryRepository.findSynsetsWithColocatedDefinitionSenseAndWord(JpaDictionaryRepository.java:772)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)

Could not resolve NativeQuery parameter type : `org.hibernate.query.internal.QueryParameterNamedImpl@68423cd`
	at org.hibernate.sql.exec.internal.JdbcParameterBindingsImpl.<init>(JdbcParameterBindingsImpl.java:78)
	at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:126)
	at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:628)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:423)
	at org.hibernate.query.Query.getResultList(Query.java:120)
	at com.rreganjr.nlp.dictionary.impl.repository.jpa.JpaDictionaryRepository.findSynsetsWithColocatedDefinitionSenseAndWord(JpaDictionaryRepository.java:767)

maybe the native sql needs to be updated.